on: [pull_request]

jobs:
  leaf_validator_job:
    runs-on: ubuntu-latest
    name: Validate pending leaves
    steps:
    - uses: actions/checkout@v2
      with:
         fetch-depth: 0
    - name: Leaf validator step
      id: leaf_validator
      uses: google/trillian-examples/serverless/deploy/github/leaf_validator@master
      with:
        log_dir: './log'
